version: '3.8'

services:
  nginx:
    image: gregogs/alchemy-gc-sa:0.1
    ports:
      - "8080:8080"
    networks:
      - net-test
    volumes:
      - ./mnt:/app
networks:
  net-test:
    driver: bridge
